Tickets/sitcom 1387
lsst-ts/observatory-ops-docs pull request #108
Opened 2024-06-14 20:12 UTC by Kelks19

This is the procedure for MTRotator recovery. The confluence page was already reviewed and vetted. This documenetation has minor grammar changes and is formatted in the required formal documentation style. 

Request final format checks and figure checks. 

PS: I need to replace Figure 1 as I found a better readable version on Docushare !

2024-06-19 17:02 UTC, isotuela requested changes
This is great! 
Only few comments related to the indentation of the sequences, to properly display this long sequence of steps. 
Also, the images location are the old folder names and they won't display. Current _static folder is Simonyi/Troubleshooting/_static. 

Thank you! 
Ioana

2024-06-19 21:36 UTC, Kelks19 commented on Simonyi/Troubleshooting/MTCS/HexRot/MTRotator-Recovery/MTRotator-Recovery.rst
> + .. figure:: /MainTel/MainTel-Troubleshooting/_static/mtrot_recovery_1.png
ok !

2024-06-19 23:20 UTC, Kelks19 commented on Simonyi/Troubleshooting/MTCS/HexRot/MTRotator-Recovery/MTRotator-Recovery.rst
> +- The difference between the MTRotator and the Camera Cable Wrap (CCW) is too large. Bulkhead limit
done!

2024-06-19 23:42 UTC, Kelks19 commented on Simonyi/Troubleshooting/MTCS/HexRot/MTRotator-Recovery/MTRotator-Recovery.rst
> +
I just corrected the tab on the line and left it as is

2024-06-20 02:17 UTC, Kelks19 commented on Simonyi/Troubleshooting/MTCS/HexRot/MTRotator-Recovery/MTRotator-Recovery.rst
> +    .. figure:: /MainTel/MainTel-Troubleshooting/_static/mtrot_recovery_3.png
I think that is because of the images not being rendered. There is no indentation mismatch with the images.

2024-06-20 06:49 UTC, Kelks19 commented on Simonyi/Troubleshooting/MTCS/HexRot/MTRotator-Recovery/MTRotator-Recovery.rst
> + .. figure:: /MainTel/MainTel-Troubleshooting/_static/mtrot_recovery_1.png
indent issue resolved once the image was rendered properly

2024-06-20 06:49 UTC, Kelks19 commented on Simonyi/Troubleshooting/MTCS/HexRot/MTRotator-Recovery/MTRotator-Recovery.rst
> +- :ref:`Safety Interlock <mtrot_recovery_5>` active in the MTRotator GUI
done

2024-06-20 14:54 UTC, Kelks19 commented on Simonyi/Troubleshooting/MTCS/HexRot/MTRotator-Recovery/MTRotator-Recovery.rst
> +    a.  Press :guilabel:`Bypass` by the D-8 (CCW Safety Device Actuated).
I am just not able to :'(

2024-06-20 20:00 UTC, Kelks19 commented on Simonyi/Troubleshooting/MTCS/HexRot/MTRotator-Recovery/MTRotator-Recovery.rst
> +    a.  Press :guilabel:`Bypass` by the D-8 (CCW Safety Device Actuated).
ok , resolved!

2024-06-20 22:54 UTC, merged