AuxTel intro page figures
lsst-ts/observatory-ops-docs pull request #119
Opened 2024-07-24 20:28 UTC by kpenaramirez

Dear colleagues,
An introductory page with figures has been deployed for AuxTel. A couple of figures and a table were incorporated. Any comment you may have would be highly appreciated.  The idea with this introductory page is to have a quick visual glance on the main AuxTel features.

[The html version of the document can be read here.](https://obs-ops.lsst.io/v/SITCOM-1356/AuxTel/index.html)

Thank you in advance.
Karla.

2024-07-24 22:11 UTC, edennihy commented on AuxTel/index.rst
> +AuxTel requires daytime and nighttime operations. Daytime operations focus on performance checks of the telescope mount, dome, mirror, mirror covers, and vents. AuxTel CSC, AuxTel instrument (LATISS)
recollected -> collected

2024-07-24 22:13 UTC, edennihy commented on AuxTel/index.rst
> +AuxTel operations can also be constrained by Sun altitude and time. Below an schematic view of the current default AuxTel observations workflow.
You might consider removing the first sentence, not sure it adds much.

2024-07-24 22:15 UTC, edennihy commented on AuxTel/index.rst
> +An observing run with AuxTel can also include a series of non-standard operations:
I'm not sure this is the right description for this section. Our non-standard operations are more like a set of rare troubleshooting or know-how articles. Observing runs can include a series of engineering operations, but we're trying very hard to move away from that so I was happy to see this page was focused on the standard, scheduler-driven observations.

2024-07-24 22:20 UTC, edennihy commented on AuxTel/index.rst
>  .. Troubleshooting
The formatting of these subsections is kind off odd in the html, I think you might need some stronger separation.

2024-07-24 22:31 UTC, edennihy commented on AuxTel/_static/AuxTel_weather_constraints.png
I really like the concept of this figure, especially putting it on the front page, but it kind of confused me. For example, when the wind is > 12m/s, I read this as the first step is to evaluate each 15min and then close. But I think you mean, close and then evaluate each 15min. So I read them as a list of steps in order going down the chart. I'm not sure everyone will see it that way, but there might be a different way to organize these to avoid this.

2024-07-24 22:34 UTC, edennihy requested changes
A few minor comments and changes to consider, thanks for putting this page together.

2024-07-25 14:53 UTC, kpenaramirez commented on AuxTel/_static/AuxTel_weather_constraints.png
I will modify the figure. The way the figure reads must be clear to everyone. Thank you for noticing it.

2024-07-29 15:54 UTC, PaulinaLSST commented
Nice work. I loved it.  Just few comment related to the organization and figures .

2024-07-29 21:44 UTC, kpenaramirez commented on AuxTel/index.rst
> +   | Daytime Checkout         | T17   | RubinTV           | #summit_announce         |
I will include it here temporarily. I think that change would need to be addressed in the Daytime Checkout page accordingly.

2024-07-29 21:46 UTC, kpenaramirez commented on AuxTel/index.rst
>     Standard-Operations/index.rst
There is a commit in the Git tree that already acknowledge this issue.

2024-07-29 22:00 UTC, kpenaramirez commented on AuxTel/_static/AuxTel_weather_constraints.svg
For building the figure I just translated the text written in the dedicated page. There is not a settled limit in humidity yet to close, 80% seems reasonable but it is not in the official documentation. I hope once the front page is up, we can return to this details and discuss it.

2024-07-29 22:11 UTC, kpenaramirez commented
Hi @edennihy and @PaulinaLSST,
Thank you for your comments. I have modified the document accordingly. Please let me know if there are pending issues I need to address to have your approval.
Best,
Karla.

2024-07-29 22:24 UTC, PaulinaLSST commented
No pending issue from my side. :)

2024-07-29 22:26 UTC, PaulinaLSST approved these changes

2024-07-29 22:53 UTC, edennihy approved these changes
Thanks for updating that figure, it is clearer for me now!

2024-08-05 02:05 UTC, isotuela approved these changes
Thank you so much, Karla! This is a great contribution to the documentation. 

In order to merge, you are going to have to rebase to `main` and squash all commits into a single commit. Let me know how it goes and wether you need assistance.

2024-08-06 20:24 UTC, kpenaramirez commented
Thanks @edennihy, @PaulinaLSST, @isotuela for the comments. I probably bother you again in the future when we attempt a similar page for Simonyi. Fingers crossed!.

2024-08-06 20:25 UTC, merged