MTPtg Configuration - tickets/SITCOM-1431
lsst-ts/observatory-ops-docs pull request #129
Opened 2024-08-27 23:27 UTC by PaulinaLSST

Hi David and Jacqueline.

I hope you're doing well. I wanted to kindly ask if you could take some time to review the work I've completed on ticket SITCOM-1431. "MTPtg Configuration for MTRotator and MTMount"

Please let me know if you have any questions 
Paulina

2024-10-09 22:40 UTC, JackieS-NL requested changes
Hi Paulina, great job with this document.

As this is a procedure it should use the procedure template. 

You need to update the changes made in the Confluence version of this document, I added 2 comments in Confluence.

Most comments are suggestions to rewrite some parts, feel free to ignore them.

Thanks!

2024-10-09 22:40 UTC, JackieS-NL commented on Simonyi/Non-Standard-Operations/MTCS/MTPtg/MTPtg-Configuration-for-MTRot-MTMount.rst
> +MTPtg Configuration for MTRotator and MTMount
As this is a procedure it should have the corresponding template

2024-10-09 22:40 UTC, JackieS-NL commented on Simonyi/Non-Standard-Operations/MTCS/MTPtg/MTPtg-Configuration-for-MTRot-MTMount.rst
> +Cases
This part maybe should be in the overview section of the procedure template

2024-10-09 22:40 UTC, JackieS-NL commented on Simonyi/Non-Standard-Operations/MTCS/MTPtg/MTPtg-Configuration-for-MTRot-MTMount.rst
> +    Announce through the Slack channel *#summit-simonyi* that the component is not available, and you are about to change the configuration.
Maybe this part should be the first step of the procedure, adding a note that it should not be skipped

2024-10-09 22:40 UTC, JackieS-NL commented on Simonyi/Non-Standard-Operations/MTCS/MTPtg/MTPtg-Configuration-for-MTRot-MTMount.rst
> +    .. figure:: ./_static/1.png
Consider displaying this image in a larger size, maybe remove, trim the command. Also highlighting the pod line will help.

2024-10-09 22:40 UTC, JackieS-NL commented on Simonyi/Non-Standard-Operations/MTCS/MTPtg/MTPtg-Configuration-for-MTRot-MTMount.rst
> +4. **Move to configuration directory,** the configuration files are one level up. The directory contains the configuration files :file:`MTPtg.info` (:file:`ATPtg.info` for AuxTel) and the pointing mo
I would rewrite this, an example: 'Move to the directory that contains the configuration files’
Or ‘Move to the configuration directory indicated below.’'

2024-10-09 22:40 UTC, JackieS-NL commented on Simonyi/Non-Standard-Operations/MTCS/MTPtg/MTPtg-Configuration-for-MTRot-MTMount.rst
> +    At startup, the pointing component loads by default the pointing model :file:`mt.mod` file and the :file:`MTPtg.info` (equivalent for AuxTel).
I would remove '(equivalent for AuxTel)' Maybe add a note of the equivalence below the procedure's steps.

2024-10-09 22:40 UTC, JackieS-NL commented on Simonyi/Non-Standard-Operations/MTCS/MTPtg/MTPtg-Configuration-for-MTRot-MTMount.rst
> +    5.1. ``MTRotator``: The **disable_rotator** line of the :file:`MTPtg.info` file contains the parameter you need to change. It reflects whether the ``MTRotator`` is monitored in the tracking.
Consider rewriting as 
'Edit the disable_rotator parameter in the MTPtg.info file
* set 1: rotator will be ignored and not be commanded by the MTPtg component (disabled)
* set 0: rotator will be considered (enabled) '

2024-10-09 22:40 UTC, JackieS-NL commented on Simonyi/Non-Standard-Operations/MTCS/MTPtg/MTPtg-Configuration-for-MTRot-MTMount.rst
> +    5.2. ``MTMount``: The line containing the **disable_mount** parameter in the :file:`MTPtg.info` file is the one to edit. It shows whether the ``MTMount`` is monitored in the tracking.
Same suggestion as previous point (step 5.1)

2024-10-09 22:40 UTC, JackieS-NL commented on Simonyi/Non-Standard-Operations/MTCS/MTPtg/MTPtg-Configuration-for-MTRot-MTMount.rst
> +* If the procedure is not successful, report the issue in *#summit-simonyi*, inform the commissioning scientist on duty, and/or activate the xxxxxxOut of Hours Support_.
Fix 'Out of hour support' link

2024-10-09 22:40 UTC, JackieS-NL commented on Simonyi/Non-Standard-Operations/MTCS/MTPtg/MTPtg-Configuration-for-MTRot-MTMount.rst
> +7. From LOVE, **send** the ``MTPtg`` back to ``ENABLED`` using the script :file:`set_summary_state.py` and configuration below. ``MTMount`` must be ``ENABLED``, even if not tracking, so ``CCW`` can b
I suggest rewriting as 
'Send the MTPtg to ENABLED using the script set_summary_state.py and configuration below in the MTQueue.
Note: MTMount must be ENABLED, even if not tracking, so CCW can be still monitored.
'

2025-04-21 21:15 UTC, JackieS-NL reviewed
Hi @PaulinaLSST , I added some comments for you to consider.

2025-05-20 18:01 UTC, dsanmartim approved these changes
Hi Paulina. 

Sorry for the long delay to review your document and thanks for putting this together. I've added a couple of short comments/suggestions, but already approved the document. Please, see my comments before merging.

2025-05-21 06:45 UTC, PaulinaLSST commented on Simonyi/Non-Standard-Operations/MTCS/MTPtg/MTPtg-Configuration-for-MTRot-MTMount.rst
> +When either the **MTRotator** or **MTMount** components become unavailable during Simonyi operations, and you still want to continue testing and tracking, it's necessary to change the configuration o
I take the full version of your suggestion

2025-05-21 06:46 UTC, PaulinaLSST commented on Simonyi/Non-Standard-Operations/MTCS/MTPtg/MTPtg-Configuration-for-MTRot-MTMount.rst
> +    Detailed `Instructions for Kubernetes`_.
done

2025-05-21 06:49 UTC, PaulinaLSST commented on Simonyi/Non-Standard-Operations/MTCS/MTPtg/MTPtg-Configuration-for-MTRot-MTMount.rst
> +      Fig3. In this particular case the name of the *MTPtg* **pod** is **mtptg-nss2j**, the name changed constantly *(mtptg-xxxxx)*.
done

2025-05-21 07:02 UTC, PaulinaLSST commented
@dsanmartim 
Hi David, thank you very much for your work and great suggestions. I’ve added all of your comments.
I can finally finish and merge this document.

2025-05-22 07:20 UTC, merged