Tickets/sitcom 1362
lsst-ts/observatory-ops-docs pull request #134
Opened 2024-09-30 18:05 UTC by Garavena89

Hello everyone!
Please review this PR about the summary table of some AuxTel common faults.
Some links remained in TBC, when ready I can add them in the correction.
Cheers!

2024-10-01 00:43 UTC, PaulinaLSST requested changes
Hi Gonzalo. I have only one comment for you. The document look great

2024-10-01 00:43 UTC, PaulinaLSST commented on AuxTel/Troubleshooting/index.rst
> +     - Identify the problematic CCS subsystem, review alerts and logs, and determine if the issue is transitory or requires expert diagnosis. Create an OBS ticket to track the problem. Clear alerts i
I have one comment. I belive the following sentence "Identify the problematic CCS subsystem, review alerts and logs, and determine if the issue is transitory or requires expert diagnosis. Create an OBS ticket to track the problem." could be removed, as this action should be conducted in any troubleshooting process."

2024-10-04 18:00 UTC, Kelks19 requested changes
I think that the columns `Troubleshooting procedure`  and `Happens mostly when` should be removed for the following reasons -- 
1. If we are unable to include 100% information then it makes no sense to have partial information -- troubleshooting is not something we can summarise else we would not have made independant pages. It will also encuorage people trying half procedures without going to the detailed page which is not good. 

I suggest to just include the link of the relevant page without giving any details 

2. None of the common faults are exclusive to specific time, or type of motion. They can occur anytime we are oerating the telescope. We have not stream-lined  the operations yet to ppolulate this column of `When it happens `. 


Suggestion : you can create a label like 'on-sky' or `target-specific` if its something thats happens when we are on sky observing e.g. WEP aligning which can lead to script issues rather than system issues ....

2024-10-07 15:13 UTC, isotuela requested changes
Thank you for putting this together. 

The column Troubleshooting Procedures should only have links to the troubleshooting pages, as mentioned before by other reviewer. It will also simplify the table. 

Instead of the column "Happens mostly" (which it was mostly venting, calibration, preparing, observing) could we include some of the traceback error to help discern which procedure to use? What do you think? 

Thank you again!

2024-10-07 17:58 UTC, isotuela commented
Can you please add a line for the fault when "ATDome shutter fails to close" and link it to the procedure already available https://obs-ops.lsst.io/AuxTel/Non-Standard-Operations/Emergency-Shutdown/Emergency-Shutdown.html ?

2024-10-10 16:50 UTC, JackieS-NL requested changes
Thank you Gonzalo for this much needed document! 

I agree with all of the reviewers comments, namely.
1. Remove ‘Happens mostly when’ column
2. Troubleshooting procedure column should have just the links for the procedures

2024-10-20 22:51 UTC, Garavena89 commented
Ok guys I did some corrections according to your comments.
- Double check all fault pages 
- Left only troubleshooting links
- Did not remove "mostly happens" column but I combined it with an Error traceback column (open to discuss)
- Not sure if we will need another page for the Whitelight issues

Let me know your thoughts :)

2024-10-21 16:43 UTC, isotuela requested changes
This looks very good to me! 
I have only one extra request, which is to reorganize the faults based on the subsystem. ATCS, LATISS, ATCalibrationSystem, like the rest of the page, or perhaps we could use the subsystem here? https://rubinobs.atlassian.net/wiki/spaces/LSSTCOM/pages/53741849/Systems+Sub-Systems+and+Components+Proposal+for+JIRA 
It could be good then ATCS/ATDome, ATCS/ATMount, ATCS/M1, AuxTel Calibration/ATWhiteLight, what do you all think?

2024-10-22 17:44 UTC, Garavena89 commented on AuxTel/Troubleshooting/index.rst
> +     - :ref:`Daytime checkout <AuxTel-DayTime-Operations-Daytime-Checkout>`
For the reorganization of the fault we should change then the title of the row for System/Sub-system instead of CSC.
It sounds good to me

2024-10-25 11:03 UTC, JackieS-NL approved these changes
This is looking great! Approved
Thanks

2024-10-25 13:45 UTC, PaulinaLSST approved these changes
This document looks great! Thanks a lot  :)

2024-10-30 18:50 UTC, isotuela reviewed
This looks great. 
Please consider naming the CSCs with the group they belong to:
 ATWhitelight to ATCalSys/ATWhiteLight
 LATISS to LATISS/ATCamera
 ATSpectrograph to LATISS/ATSpectrograph
ATCS ATCS/ATHexapod
AT Dome to ATCS/ATDome
AT Mount to ATCS/ATMCS


And perhaps reorganizing the table to position
 LATISS/ATCamera and LATISS/ATSpectrograph next to each other 
 
It's approved otherwise, remember to rebase and squash all commits into 1. 
Thank you!
Ioana

2024-11-20 17:40 UTC, isotuela approved these changes
Squashed and link to video updated.

2024-11-27 18:27 UTC, merged